name             'uamsclient'
maintainer       'SolarWinds'
maintainer_email 'support@solarwinds.com'
license          'MIT'
description      'Installs UAMS Client - agent for SolarWinds Observability platform'
version          '0.1.0'
chef_version     '>= 16.0'
source_url       'https://github.com/solarwinds/uamsclient-chef'
issues_url       'https://github.com/solarwinds/uamsclient-chef/issues'
