name             'uamsclient'
maintainer       'SolarWinds'
maintainer_email 'support@solarwinds.com'
license          'MIT'
description      'Installs UAMS Client - agent for SolarWinds Observability platform'
version          '0.5.0'
chef_version     '>= 16.0'
source_url       'https://github.com/solarwinds/uamsclient-chef'
issues_url       'https://github.com/solarwinds/uamsclient-chef/issues'

supports 'ubuntu', '>= 18.04'
supports 'debian', '>= 9.0'
supports 'redhat', '>= 7.0'
supports 'centos', '>= 7.0'
supports 'fedora', '>= 32.0'
supports 'kali', '>= 2021.0'
supports 'oracle', '>= 8.0'
supports 'windows', '>= 10.0'
